# 多环境配置
dev: # 开发环境
    base_url: "http://localhost:8080"
    api_url: "http://localhost:3000/api"
    users:
        admin:
            username: "admin"
            password: "test1234"
        test_user:
            username: "test@dev.com"
            password: "test123"
    database:
        host: "localhost"
        port: 3306
        name: "dev_db"
    webdriver:
        mode: "local" # 运行模式: `grid` 或 `local` (默认)
        grid_hub_url: "http://localhost:4444/wd/hub" # Grid Hub地址
        browser: "chrome" # 指定浏览器: chrome, firefox, edge
        headless: false # 无头模式 (Grid模式下，部分Node可能已预设)
        timeout: 10 # 隐式等待时间
        record_video: false # 是否录制视频

test: # 测试环境
    base_url: "http://webautotest-jpress-1:8080"
    api_url: "https://test-api.example.com"
    users:
        admin:
            username: "admin"
            password: "test1234"
        test_user:
            username: "test@test.com"
            password: "test456"
    database:
        host: "test-db.example.com"
        port: 3306
        name: "test_db"
    webdriver:
        mode: "grid" # 运行模式: `grid` 或 `local` (默认)
        grid_hub_url: "http://localhost:4444/wd/hub" # Grid Hub地址
        browser: "chrome" # 指定浏览器: chrome, firefox, edge
        headless: false # 无头模式 (Grid模式下，部分Node可能已预设)
        timeout: 15 # 隐式等待时间
        record_video: true # 是否录制视频

prod: # 生产环境
    base_url: "https://example.com"
    api_url: "https://api.example.com"
    users:
        admin:
            username: "admin@prod.com"
            password: "${PROD_ADMIN_PASS}" # 从环境变量读取
        test_user:
            username: "test@prod.com"
            password: "${PROD_TEST_PASS}"
    database:
        host: "prod-db.example.com"
        port: 3306
        name: "prod_db"
    webdriver:
        mode: "grid" # 运行模式: `grid` 或 `local` (默认)
        grid_hub_url: "http://selenium-hub:4444/wd/hub" # Grid Hub地址
        browser: "chrome" # 指定浏览器: chrome, firefox, edge
        headless: true # 无头模式 (Grid模式下，部分Node可能已预设)
        timeout: 20 # 隐式等待时间
        record_video: false # 是否录制视频
